name             'ruby-appraiser'
maintainer       'James FitzGibbon'
maintainer_email 'james@nadt.net'
license          'All rights reserved'
description      'Installs ruby-appraiser using chef-cligem'
version          '0.1.0'
depends          'cligem'
depends          'rbenv', '= 0.7.2'
depends          'ruby_build', '~> 0.8'
conflicts        'rbenv', '> 0.7.2'
